//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NaturalPersons
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NaturalPersons()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.NaturalPersons", typeof(NaturalPersons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string FullName
        {
            get
            {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }

        public static string NationalCode
        {
            get
            {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }

        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        public static string MobileNumber
        {
            get
            {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }

        public static string State
        {
            get
            {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        public static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        public static string Region
        {
            get
            {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }

        public static string Street
        {
            get
            {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }

        public static string Plaque
        {
            get
            {
                return ResourceManager.GetString("Plaque", resourceCulture);
            }
        }

        public static string Floor
        {
            get
            {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }

        public static string InstallationLocation
        {
            get
            {
                return ResourceManager.GetString("InstallationLocation", resourceCulture);
            }
        }

        public static string GasometerType
        {
            get
            {
                return ResourceManager.GetString("GasometerType", resourceCulture);
            }
        }

        public static string GasometerNumber
        {
            get
            {
                return ResourceManager.GetString("GasometerNumber", resourceCulture);
            }
        }

        public static string PersonNumber
        {
            get
            {
                return ResourceManager.GetString("PersonNumber", resourceCulture);
            }
        }

        public static string EmailAddress
        {
            get
            {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        public static string Attachment
        {
            get
            {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }

        public static string InstallerUserName
        {
            get
            {
                return ResourceManager.GetString("InstallerUserName", resourceCulture);
            }
        }

        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        public static string PostalCode
        {
            get
            {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
    }
}
