//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReplacementHeater {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ReplacementHeater() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.ReplacementHeater", typeof(ReplacementHeater).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HeaterInstalledType {
            get {
                return ResourceManager.GetString("HeaterInstalledType", resourceCulture);
            }
        }
        
        public static string HeaterInstalledSerialNumber {
            get {
                return ResourceManager.GetString("HeaterInstalledSerialNumber", resourceCulture);
            }
        }
        
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        public static string InstallationDate {
            get {
                return ResourceManager.GetString("InstallationDate", resourceCulture);
            }
        }
        
        public static string InstallationTime {
            get {
                return ResourceManager.GetString("InstallationTime", resourceCulture);
            }
        }
        
        public static string ScrapHeaterSerialNumber {
            get {
                return ResourceManager.GetString("ScrapHeaterSerialNumber", resourceCulture);
            }
        }
        
        public static string ScrapHeaterType {
            get {
                return ResourceManager.GetString("ScrapHeaterType", resourceCulture);
            }
        }
    }
}
